version: 2
updates:
  - package-ecosystem: "NuGet"
    directory: "/Apps"
    schedule:
      interval: "weekly"

  - package-ecosystem: "Npm"
    directory: "/Apps"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
