kind: Secret
apiVersion: v1
metadata:
  name: {{ include "waitingqueue.fullname" . }}
  labels:
    {{- include "waitingqueue.labels" . | nindent 4 }}
type: Opaque
data:
  RedisConnection: {{ default "" .Values.Secrets.RedisConnection | b64enc }}
  RoomHealthGateway__PrivateKey: {{ default "" .Values.Secrets.RoomHealthGateway__PrivateKey | b64enc }}
  