settings:
  room: HealthGatewayDev
  legacyBrowser: true
  redirectUrl: http://localhost:8000/i
  pollUrl: /Ticket
  refreshUrl: /Ticket/check-in

locales:
  ja:
    appName: "&#24453;&#21512;&#23460"
    componentFallbackText: "&#12371;&#12398;&#12467;&#12531;&#12509;&#12540;&#12493;&#12531;&#12488;&#12434;&#23455;&#34892;&#12377;&#12427;&#12395;&#12399;&#12289;JavaScript&#12434;&#26377;&#21177;&#12395;&#12377;&#12427;&#24517;&#35201;&#12364;&#12354;&#12426;&#12414;&#12377"
    errorRetryText: "&#20877;&#35430;&#34892"
    errorText: "&#12456;&#12521;&#12540;&#12364;&#30330;&#29983;&#12375;&#12414;&#12375;&#12383"
    errorTitle: BC&#24030;&#20154;&#21475;&#32113;&#35336;&#35519;&#26619;&#12399;&#29694;&#22312;&#12289;&#12450;&#12463;&#12475;&#12473;&#37327;&#12364;&#22810;&#12367;&#12289;&#36933;&#24310;&#12364;&#30330;&#29983;&#12375;&#12390;&#12356;&#12414;&#12377;&#12290
    redirectText: "&#35373;&#23450;&#12364;&#23436;&#20102;&#12375;&#12414;&#12375;&#12383;&#12290;&#12522;&#12480;&#12452;&#12524;&#12463;&#12488;&#20013;&#12290"
    statusPositionText: "&#29694;&#22312;&#12354;&#12394;&#12383;&#12398;&#38918;&#30058;&#12399;"
    statusTitle: "&#35519;&#26619;&#12471;&#12473;&#12486;&#12512;&#12399;&#29694;&#22312;&#12289;&#12450;&#12463;&#12475;&#12473;&#37327;&#12364;&#22810;&#12367;&#12289;&#12354;&#12394;&#12383;&#12399;&#12289;&#12461;&#12517;&#12540;&#12395;&#20006;&#12435;&#12391;&#12356;&#12414;&#12377;&#12290"
    title: BC Demographic Survey in Japanese
    incidentTitle: "&#20877;&#35430;&#34892 (ja) The BC General Survey is currently unavailable."
    incidentText: (ja) We are working to fix this as quickly as possible.
  en-CA:
    appName: Waiting Room
    title: BC General Survey
    errorText: Something went wrong
    incidentTitle: The BC General Survey is currently unavailable. (&#20877;&#35430;&#34892;)
    incidentText: We are working to fix this as quickly as possible.
    componentFallbackText: You need JavaScript enabled to run this component
    statusTitle: The Survey System is currently experiencing high demand and have placed you in a queue.
    statusPositionText: "Your current position in our queue is:"
    errorTitle: BC General Survey is currently experiencing high demand which is causing delays.
    errorRetryText: Retry
    redirectText: You're all set, redirecting...
  fr-CA:
    appName: Waiting Room
    title: Enquête générale de la Colombie-Britannique
    errorText: Quelque chose s'est mal passé
    incidentTitle: L'enquête démographique de la Colombie-Britannique n'est pas disponible actuellement.
    incidentText: Nous nous efforçons de résoudre ce problème le plus rapidement possible.
    componentFallbackText: Vous devez activer JavaScript pour exécuter ce composant
    statusTitle: Le système de sondage connaît actuellement une forte demande et vous a placé dans une file d'attente.
    statusPositionText: "Votre position actuelle dans notre file d'attente est :"
    errorTitle: BC General Survey connaît actuellement une forte demande, ce qui entraîne des retards.
    errorRetryText: Refaire
    redirectText: Vous êtes prêt, redirection...
