settings:
  room: HealthGatewayDev
  legacyBrowser: true
  redirectUrl: http://localhost:8000/i
  pollUrl: /Ticket
  refreshUrl: /Ticket/check-in
locales:
  en-CA:
    appName: Waiting Room
    title: BC General Survey
    errorText: Something went wrong
    incidentTitle: The BC General Survey is currently unavailable.
    incidentText: We are working to fix this as quickly as possible.
    componentFallbackText: You need JavaScript enabled to run this component
    statusTitle: The Survey System is currently experiencing high demand and have placed you in a queue.
    statusPositionText: "Your current position in our queue is:"
    errorTitle: BC General Survey is currently experiencing high demand which is causing delays.
    errorRetryText: Retry
    redirectText: You're all set, redirecting...
  fr-CA:
    appName: Waiting Room
    title: Enquête générale de la Colombie-Britannique
    errorText: Quelque chose s'est mal passé
    incidentTitle: L'enquête démographique de la Colombie-Britannique n'est pas disponible actuellement.
    incidentText: Nous nous efforçons de résoudre ce problème le plus rapidement possible.
    componentFallbackText: Vous devez activer JavaScript pour exécuter ce composant
    statusTitle: Le système de sondage connaît actuellement une forte demande et vous a placé dans une file d'attente.
    statusPositionText: "Votre position actuelle dans notre file d'attente est :"
    errorTitle: BC General Survey connaît actuellement une forte demande, ce qui entraîne des retards.
    errorRetryText: Refaire
    redirectText: Vous êtes prêt, redirection...
