settings:
  room: HealthGatewayDev
  legacyBrowser: true
  redirectUrl: http://localhost:8001/i
  pollUrl: /Ticket
  refreshUrl: /Ticket/check-in

locales:
  ja:
    appName: "\u5F85\u5408\u5BA4"
    componentFallbackText: "\u3053\u306E\u30B3\u30F3\u30DD\u30FC\u30CD\u30F3\u30C8\
      \u3092\u5B9F\u884C\u3059\u308B\u306B\u306F\u3001JavaScript\u3092\u6709\u52B9\
      \u306B\u3059\u308B\u5FC5\u8981\u304C\u3042\u308A\u307E\u3059"
    errorRetryText: "\u518D\u8A66\u884C"
    errorText: "\u30A8\u30E9\u30FC\u304C\u767A\u751F\u3057\u307E\u3057\u305F"
    errorTitle: "BC\u5DDE\u4EBA\u53E3\u7D71\u8A08\u8ABF\u67FB\u306F\u73FE\u5728\u3001\
      \u30A2\u30AF\u30BB\u30B9\u91CF\u304C\u591A\u304F\u3001\u9045\u5EF6\u304C\u767A\
      \u751F\u3057\u3066\u3044\u307E\u3059\u3002"
    incidentText: (\u5F85\u5408\u5BA4) JP We are working to fix this as quickly as possible.
    incidentTitle: JP The BC Demographic Survey is currently unavailable.
    redirectText: "\u8A2D\u5B9A\u304C\u5B8C\u4E86\u3057\u307E\u3057\u305F\u3002\u30EA\
      \u30C0\u30A4\u30EC\u30AF\u30C8\u4E2D\u3002"
    statusPositionText: "\u73FE\u5728\u3042\u306A\u305F\u306E\u9806\u756A\u306F"
    statusTitle: "\u8ABF\u67FB\u30B7\u30B9\u30C6\u30E0\u306F\u73FE\u5728\u3001\u30A2\
      \u30AF\u30BB\u30B9\u91CF\u304C\u591A\u304F\u3001\u3042\u306A\u305F\u306F\u3001\
      \u30AD\u30E5\u30FC\u306B\u4E26\u3093\u3067\u3044\u307E\u3059\u3002"
    title: "JP BC\u5DDE\_\u4EBA\u53E3\u7D71\u8A08\_\u8ABF\u67FB"
  en-CA:
    appName: Waiting Room
    title: BC General Survey
    errorText: Something went wrong
    incidentTitle: The BC General Survey is currently unavailable. (&#20877;&#35430;&#34892;)
    incidentText: We are working to fix this as quickly as possible.
    componentFallbackText: You need JavaScript enabled to run this component
    statusTitle: The Survey System is currently experiencing high demand and have placed you in a queue.
    statusPositionText: "Your current position in our queue is:"
    errorTitle: BC General Survey is currently experiencing high demand which is causing delays.
    errorRetryText: Retry
    redirectText: You're all set, redirecting...
  fr-CA:
    appName: Waiting Room
    title: Enquête générale de la Colombie-Britannique
    errorText: Quelque chose s'est mal passé
    incidentTitle: L'enquête démographique de la Colombie-Britannique n'est pas disponible actuellement.
    incidentText: Nous nous efforçons de résoudre ce problème le plus rapidement possible.
    componentFallbackText: Vous devez activer JavaScript pour exécuter ce composant
    statusTitle: Le système de sondage connaît actuellement une forte demande et vous a placé dans une file d'attente.
    statusPositionText: "Votre position actuelle dans notre file d'attente est :"
    errorTitle: BC General Survey connaît actuellement une forte demande, ce qui entraîne des retards.
    errorRetryText: Refaire
    redirectText: Vous êtes prêt, redirection...
