/** @type Record<string, string> */
export const languages = {
  "en-CA": "English",
  "fr": "Français",
  "fr-CA": "Français",
  "pa": "ਪੰਜਾਬੀ",
  "pa-IN": "ਪੰਜਾਬੀ",
  "zh": "\u{4E2D}\u{6587} (\u{53F0}\u{7063})",
  "zz": "\u{4E2D}\u{6587} (\u{4E2D}\u{56FD})",
  "zh-CN": "中文 (中国)",
  "zh-TW": "中文 (台灣)",
  "ko": "한국어",
  "ko-KR": "한국어",
  tl: "Tagalog",
  "fa": "فارسی",
  "fa-IR": "فارسی",
  "es": "Español",
  "es-ES": "Español",
  vi: "Tiếng Việt",
  "hi": "हिन्दी",
  "hi-IN": "हिन्दी",
  ar: "العربية",
  ja: "日本語",
  pt: "Português",
  "pt-PT": "Português",
  ur: "اردو",
};
