apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |
      The role based settings to allow OpenShift Dev, Test, and Prod to pull images from tools.
  name: rbac-image-management
objects:
  - apiVersion: authorization.openshift.io/v1
    groupNames:
      - system:serviceaccounts:${PULL_PROJECT}
    kind: RoleBinding
    metadata:
      name: ${LICENSE}-${SERVICE_ACCOUNT}-pull:image-pullers
      namespace: ${PULL_PROJECT}
      labels:
        app: ${SERVICE_ACCOUNT}
    roleRef:
      name: system:image-puller
    subjects:
      - kind: SystemGroup
        name: system:serviceaccounts:${PULL_PROJECT}
      - kind: ServiceAccount
        name: "${SERVICE_ACCOUNT}"
        namespace: ${LICENSE}-dev
      - kind: ServiceAccount
        name: "${SERVICE_ACCOUNT}"
        namespace: ${LICENSE}-test
      - kind: ServiceAccount
        name: "${SERVICE_ACCOUNT}"
        namespace: ${LICENSE}-prod
    userNames:
      - system:serviceaccount:${LICENSE}-dev:${SERVICE_ACCOUNT}
      - system:serviceaccount:${LICENSE}-test:${SERVICE_ACCOUNT}
      - system:serviceaccount:${LICENSE}-prod:${SERVICE_ACCOUNT}

parameters:
  - name: LICENSE
    displayName: The license plate prefix
    description: The license plate prefix to be used to identify the dev test and prod environments
    required: true
  - name: PULL_PROJECT
    displayName: The project to allow pull access
    description: The project to allow other projects to pull from typically xxx-tools
    required: true
  - name: SERVICE_ACCOUNT
    displayName: The project to allow pull access
    description: The project to allow other projects to pull from
    required: true
    value: githubbuilder
