name: admin-ci

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - Apps/Admin/**
      - .github/workflows/admin-ci.yml
      - .github/workflows/ci-template.yml

jobs:
  CI:
    uses: ./.github/workflows/ci-template.yml
    with:
      DOCKER_CONTEXT: Apps/Admin
      DOCKER_FILE: Apps/Admin/Dockerfile