name: frontend-ci

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - Apps/Frontend/**
      - .github/workflows/frontend-ci.yml
      - .github/workflows/ci-template.yml

jobs:
  CI:
    uses: ./.github/workflows/ci-template.yml
    with:
      DOCKER_CONTEXT: Apps/Frontend
      DOCKER_FILE: Apps/Frontend/Dockerfile
